// src/styles/authStyles.js
export const authStyles = {
    page: {
        position: "fixed",
        top: 0,
        left: 0,
        width: "100vw",
        height: "100vh",
        overflow: "hidden",
        display: "flex",
        flexDirection: "column",
        background: "linear-gradient(135deg, #faf5ff 0%, #f3e8ff 40%, #fce7f3 100%)",
        fontFamily:
            "'Inter', -apple-system, BlinkMacSystemFont, 'Segoe UI', Roboto, 'Helvetica Neue', Arial, sans-serif",
        boxSizing: "border-box",
        zIndex: 999999, // optional but recommended
    },

    blob1: {
        position: "absolute",
        top: -120,
        right: -80,
        width: 400,
        height: 400,
        borderRadius: "50%",
        background:
            "radial-gradient(circle, rgba(167,139,250,0.25) 0%, transparent 70%)",
        pointerEvents: "none",
        animation: "auth-blob 8s ease-in-out infinite",
    },
    blob2: {
        position: "absolute",
        bottom: -100,
        left: -60,
        width: 350,
        height: 350,
        borderRadius: "50%",
        background:
            "radial-gradient(circle, rgba(236,72,153,0.15) 0%, transparent 70%)",
        pointerEvents: "none",
        animation: "auth-blob 10s ease-in-out infinite reverse",
    },
    blob3: {
        position: "absolute",
        top: "40%",
        left: "30%",
        width: 300,
        height: 300,
        borderRadius: "50%",
        background:
            "radial-gradient(circle, rgba(124,58,237,0.08) 0%, transparent 70%)",
        pointerEvents: "none",
    },
    header: {
        padding: "24px 32px 0",
        display: "flex",
        justifyContent: "center",
        position: "relative",
        zIndex: 1,
    },
    brand: {
        display: "flex",
        alignItems: "center",
        gap: 12,
    },
    logoBox: {
        width: 44,
        height: 44,
        borderRadius: 14,
        background: "linear-gradient(135deg, #7c3aed 0%, #a78bfa 100%)",
        display: "flex",
        alignItems: "center",
        justifyContent: "center",
        boxShadow: "0 4px 16px rgba(124,58,237,0.3)",
    },
    siteName: {
        fontSize: 22,
        fontWeight: 800,
        color: "#4c1d95",
        letterSpacing: -0.5,
        lineHeight: 1,
    },
    siteTag: {
        fontSize: 12,
        color: "#8b5cf6",
        marginTop: 2,
        fontWeight: 500,
    },
    centerArea: {
        flex: 1,
        display: "flex",
        justifyContent: "center",
        alignItems: "center",
        padding: "24px 20px",
        gap: 40,
        position: "relative",
        zIndex: 1,
    },
    leftPanel: {
        width: 320,
        flexShrink: 0,
        display: "none",
    },
    leftPanelContent: {
        padding: "32px",
        background: "rgba(255,255,255,0.6)",
        borderRadius: 24,
        backdropFilter: "blur(20px)",
        boxShadow: "0 4px 24px rgba(124,58,237,0.1)",
        border: "1px solid rgba(255,255,255,0.8)",
    },
    leftTitle: {
        fontSize: 22,
        fontWeight: 700,
        color: "#1e1b4b",
        margin: "0 0 10px",
        lineHeight: 1.3,
    },
    leftDesc: {
        fontSize: 14,
        color: "#6b7280",
        lineHeight: 1.6,
        margin: "0 0 20px",
    },
    featureList: {
        display: "flex",
        flexDirection: "column",
        gap: 10,
    },
    featureItem: {
        display: "flex",
        alignItems: "center",
        gap: 10,
        fontSize: 14,
        color: "#374151",
        fontWeight: 500,
    },
    featureDot: {
        width: 8,
        height: 8,
        borderRadius: "50%",
        background: "linear-gradient(135deg, #7c3aed, #a78bfa)",
        flexShrink: 0,
    },
    card: {
        width: "100%",
        maxWidth: 600, // Widened to match iCloud's horizontal proportion
        minHeight: "auto", // Prevents the card from being a tall rectangle
        borderRadius: 28,
        background: "rgba(255,255,255,0.98)",
        boxShadow: "0 20px 60px rgba(0,0,0,0.05)",
        backdropFilter: "blur(20px)",
        border: "1px solid #ffffff",
        display: "flex",
        flexDirection: "column",
        alignItems: "center",
        overflow: "hidden",
        boxSizing: "border-box",
        paddingBottom: 24,
    },
    sliderViewport: {
        width: "100%",
        overflow: "hidden",
        display: "block",
        boxSizing: "border-box",
    },
    panelIcon: {
        fontSize: 36,
        marginBottom: 10,
    },
    title: {
        marginBottom: 6,
        fontWeight: 800,
        fontSize: 24,
        color: "#1e1b4b",
        letterSpacing: -0.5,
        textAlign: "center",
    },
    subtitle: {
        fontSize: 14,
        color: "#9ca3af",
        margin: "0 0 24px",
        textAlign: "center",
        fontWeight: 400,
    },
    fieldGroup: {
        width: "100%",
        maxWidth: 340, // Keeps content centered with wide margins
        marginBottom: 14,
    },
    fieldLabel: {
        display: "block",
        fontSize: 12,
        fontWeight: 700,
        color: "#6b7280",
        marginBottom: 6,
        letterSpacing: 0.4,
        textTransform: "uppercase",
    },
    input: {
        width: "100%",
        height: 48, // Fixed height prevents stretching
        padding: "0 16px",
        borderRadius: 12,
        fontSize: 16,
        outline: "none",
        boxSizing: "border-box",
        background: "#ffffff",
        border: "1.5px solid #d2d2d7",
        color: "#1d1d1f",
        transition: "border-color 0.2s",
    },
    rowBetween: {
        width: "100%",
        maxWidth: 360,
        display: "flex",
        justifyContent: "space-between",
        alignItems: "center",
        marginBottom: 16,
    },
    checkboxLabel: {
        display: "flex",
        alignItems: "center",
        color: "#374151",
        fontSize: 13,
        fontWeight: 500,
        cursor: "pointer",
    },
    linkButton: {
        background: "transparent",
        border: "none",
        color: "#7c3aed",
        cursor: "pointer",
        fontSize: 13,
        fontWeight: 600,
        textDecoration: "none",
        padding: 0,
        fontFamily: "inherit",
    },
    button: {
        width: "100%",
        maxWidth: 340,
        height: 48, // LOCKS the height to a normal size
        borderRadius: 12,
        border: "none",
        background: "linear-gradient(135deg, #7c3aed 0%, #a78bfa 100%)",
        color: "white",
        fontSize: 16,
        fontWeight: 600,
        cursor: "pointer",
        marginTop: 12,
        display: "flex",
        justifyContent: "center",
        alignItems: "center",
        fontFamily: "inherit",
    },
    buttonSecondary: {
        flex: 1,
        padding: "13px 20px",
        borderRadius: 12,
        border: "1.5px solid #e5e7eb",
        background: "#f9fafb",
        color: "#374151",
        fontSize: 15,
        fontWeight: 600,
        cursor: "pointer",
        marginTop: 4,
        fontFamily: "inherit",
    },
    message: {
        marginTop: 12,
        color: "#ef4444",
        minHeight: 20,
        fontSize: 13,
        textAlign: "center",
        fontWeight: 500,
    },
    switchText: {
        marginTop: 20,
        color: "#9ca3af",
        fontSize: 14,
        textAlign: "center",
    },
    switchLink: {
        color: "#7c3aed",
        cursor: "pointer",
        fontWeight: 700,
        textDecoration: "none",
    },
    criteria: {
        width: "100%",
        maxWidth: 360,
        marginTop: 4,
        marginBottom: 12,
        textAlign: "left",
        background: "#faf5ff",
        borderRadius: 12,
        padding: "12px 14px",
        boxSizing: "border-box",
    },
    footer: {
        borderTop: "1px solid rgba(124,58,237,0.08)",
        background: "rgba(255,255,255,0.7)",
        padding: "12px 24px",
        backdropFilter: "blur(10px)",
        position: "relative",
        zIndex: 1,
    },
    footerInner: {
        maxWidth: 980,
        margin: "0 auto",
        display: "flex",
        justifyContent: "space-between",
        alignItems: "center",
        gap: 12,
        fontSize: 13,
        color: "#6b7280",
    },
    statusDot: {
        width: 8,
        height: 8,
        borderRadius: 999,
        background: "#10b981",
        boxShadow: "0 0 6px rgba(16,185,129,0.4)",
    },
    statusText: { color: "#374151", fontSize: 13 },
    copy: { color: "#9ca3af", fontSize: 13 },
    loadingOverlay: {
        position: "fixed",
        inset: 0,
        display: "flex",
        justifyContent: "center",
        alignItems: "center",
        background: "rgba(245,243,255,0.7)",
        backdropFilter: "blur(8px)",
        zIndex: 9999,
    },
    spinnerWrap: {
        display: "flex",
        flexDirection: "column",
        alignItems: "center",
        background: "white",
        borderRadius: 20,
        padding: "28px 36px",
        boxShadow: "0 12px 40px rgba(124,58,237,0.15)",
    },
    spinner: {
        width: 44,
        height: 44,
        borderRadius: "50%",
        border: "4px solid #ede9fe",
        borderTopColor: "#7c3aed",
        animation: "auth-spin 0.8s linear infinite",
    },
};
